# Generated by Django 4.2.13 on 2024-06-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketing', '0012_pedido_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
