# Generated by Django 4.2.13 on 2024-06-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMarketing', '0013_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
